/**
 * Assemble a complete LaTeX document from the six documentation sections.
 *
 * Mermaid diagrams (which are SVG/canvas in the browser) cannot be rendered
 * by pdflatex. Instead we include the raw diagram definition inside a
 * lstlisting environment so the content is still present but clearly labelled.
 * ASCII-flow sequences that have mermaid blocks get the same treatment.
 */
import { markdownToLatex } from './markdown-to-latex'
import { escLaTeX } from './escape'
import type { SectionKey } from '@/core/types/job'

interface SectionInput {
  key: SectionKey
  label: string
  content: string
}

const SECTION_LABELS: Record<SectionKey, string> = {
  explanation:   'Explanation',
  diagram_arch:  'Architecture Diagram',
  diagram_sub:   'Subsystem Diagrams',
  hld:           'High-Level Design',
  lld:           'Low-Level Design',
  api_flows:     'API Flows',
  glossary:      'Glossary',
}

/** Strip the mermaid fence and expose raw diagram syntax for lstlisting. */
function extractMermaidBlocks(content: string): string {
  return content.replace(
    /```mermaid\n([\s\S]*?)```/g,
    (_, def) =>
      `\\begin{lstlisting}[language={},caption={Mermaid diagram source}]\n${def.trim()}\n\\end{lstlisting}`,
  )
}

/** Convert a single section to LaTeX body content. */
function sectionToLatex(key: SectionKey, content: string): string {
  if (!content?.trim()) return ''

  const label = escLaTeX(SECTION_LABELS[key] ?? key)

  switch (key) {
    case 'diagram_arch':
    case 'diagram_sub': {
      // Expose mermaid as lstlisting; render remaining prose as markdown
      const processed = extractMermaidBlocks(content)
      return `\\section{${label}}\n\n${markdownToLatex(processed)}`
    }
    case 'api_flows': {
      // Same pattern — mermaid sequence diagrams live here too
      const processed = extractMermaidBlocks(content)
      return `\\section{${label}}\n\n${markdownToLatex(processed)}`
    }
    case 'lld': {
      // Code-heavy; trust markdownToLatex's lstlisting handling
      return `\\section{${label}}\n\n${markdownToLatex(content)}`
    }
    case 'hld':
    case 'glossary':
    default: {
      return `\\section{${label}}\n\n${markdownToLatex(content)}`
    }
  }
}

export function buildLatexDocument(params: {
  owner: string
  repo:  string
  sections: Partial<Record<SectionKey, string>>
}): string {
  const { owner, repo, sections } = params

  const DOC_SECTIONS: SectionKey[] = [
    'diagram_arch',
    'diagram_sub',
    'hld',
    'lld',
    'api_flows',
    'glossary',
  ]

  const bodyParts = DOC_SECTIONS
    .filter(k => !!sections[k])
    .map(k => sectionToLatex(k, sections[k]!))
    .join('\n\n\\newpage\n\n')

  const titleEsc = escLaTeX(`${owner}/${repo}`)
  const dateStr  = new Date().toISOString().slice(0, 10)

  return `\\documentclass[11pt,a4paper]{article}

% ─── Encoding & fonts ────────────────────────────────────────────────────────
\\usepackage[T1]{fontenc}
\\usepackage[utf8]{inputenc}
\\usepackage{lmodern}

% ─── Page geometry ───────────────────────────────────────────────────────────
\\usepackage[margin=2.5cm]{geometry}

% ─── Colours ─────────────────────────────────────────────────────────────────
\\usepackage[table]{xcolor}
\\definecolor{amber}{RGB}{195,140,40}
\\definecolor{darkbg}{RGB}{10,9,8}
\\definecolor{codebg}{RGB}{22,21,18}

% ─── Code listings ───────────────────────────────────────────────────────────
\\usepackage{listings}
\\lstset{
  backgroundcolor=\\color{codebg},
  basicstyle=\\ttfamily\\small\\color{white!85!black},
  breaklines=true,
  breakatwhitespace=false,
  frame=single,
  rulecolor=\\color{white!20!black},
  framesep=4pt,
  xleftmargin=8pt,
  xrightmargin=8pt,
}

% ─── Tables ──────────────────────────────────────────────────────────────────
\\usepackage{longtable}
\\usepackage{booktabs}
\\usepackage{array}

% ─── Misc utilities ──────────────────────────────────────────────────────────
\\usepackage{parskip}
\\usepackage{microtype}
\\usepackage{hyperref}
\\hypersetup{
  colorlinks=true,
  linkcolor=amber,
  urlcolor=amber,
}

% ─── Header / footer ─────────────────────────────────────────────────────────
\\usepackage{fancyhdr}
\\pagestyle{fancy}
\\fancyhf{}
\\lhead{\\small\\texttt{${titleEsc}}}
\\rhead{\\small\\texttt{explaincodebasepls}}
\\cfoot{\\thepage}
\\renewcommand{\\headrulewidth}{0.4pt}

% ─── Document ────────────────────────────────────────────────────────────────
\\begin{document}

\\begin{titlepage}
  \\vspace*{4cm}
  \\begin{center}
    {\\Huge\\bfseries ${titleEsc}}\\\\[1.5em]
    {\\Large Technical Documentation}\\\\[0.8em]
    {\\normalsize Generated by \\texttt{explaincodebasepls}}\\\\[0.3em]
    {\\small\\texttt{${dateStr}}}
  \\end{center}
  \\vfill
\\end{titlepage}

\\tableofcontents
\\newpage

${bodyParts}

\\end{document}
`
}
